version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: alerting_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/alerting_platform
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/alerting_platform
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/alerting_platform
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data: