# Generated by Django 5.2.6 on 2025-09-25 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='visible_to_teams',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='users.team'),
        ),
        migrations.AddField(
            model_name='alert',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useralertpreference',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='useralertpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useralertpreference',
            unique_together={('user', 'alert')},
        ),
    ]
